-- 코드를 입력하세요
SELECT AI.ANIMAL_ID, AI.ANIMAL_TYPE, AI.NAME FROM ANIMAL_INS AS AI
LEFT JOIN ANIMAL_OUTS AS AO
ON AI.ANIMAL_ID = AO.ANIMAL_ID
WHERE (AO.ANIMAL_ID IS NOT NULL AND AI.ANIMAL_ID IS NOT NULL)
AND 
(AI.SEX_UPON_INTAKE LIKE '%Intact%' AND AO.SEX_UPON_OUTCOME NOT LIKE '%Intact%')
ORDER BY AI.ANIMAL_ID
